// <auto-generated />
using ITIAcademy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIAcademy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707231619_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIAcademy.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("INT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("INT");

                    b.Property<int>("MinDegree")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DepartmentId = 1,
                            Hours = 30,
                            MinDegree = 50,
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            DepartmentId = 2,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            DepartmentId = 3,
                            Hours = 35,
                            MinDegree = 50,
                            Name = "Web Development"
                        });
                });

            modelBuilder.Entity("ITIAcademy.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Manager")
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Dr. Maha Ali",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Dr. Ahmed Hassan",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Dr. Sara Maged",
                            Name = "Software Development"
                        });
                });

            modelBuilder.Entity("ITIAcademy.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<int>("Salary")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            CourseId = 1,
                            DepartmentId = 1,
                            ImageURL = "1.png",
                            Name = "Mahmoud Ali",
                            Salary = 5000
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York, USA",
                            CourseId = 2,
                            DepartmentId = 2,
                            ImageURL = "1.png",
                            Name = "Jane Smith",
                            Salary = 4500
                        },
                        new
                        {
                            Id = 3,
                            Address = "Los Angeles, USA",
                            CourseId = 3,
                            DepartmentId = 3,
                            ImageURL = "1.png",
                            Name = "Bob Johnson",
                            Salary = 4700
                        },
                        new
                        {
                            Id = 4,
                            Address = "Miami, USA",
                            CourseId = 1,
                            DepartmentId = 1,
                            ImageURL = "2.png",
                            Name = "Alice Brown",
                            Salary = 4800
                        });
                });

            modelBuilder.Entity("ITIAcademy.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            DepartmentId = 1,
                            Grade = "Level 1",
                            ImageURL = "1.png",
                            Name = "Ahmed Ali"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            DepartmentId = 2,
                            Grade = "Level 2",
                            ImageURL = "2.png",
                            Name = "Sara Mohamed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            DepartmentId = 3,
                            Grade = "Level 3",
                            ImageURL = "1.png",
                            Name = "Omar Hassan"
                        });
                });

            modelBuilder.Entity("ITIAcademy.Models.TraineeCourse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("INT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("TraineeCourses");
                });

            modelBuilder.Entity("ITIAcademy.Models.Course", b =>
                {
                    b.HasOne("ITIAcademy.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITIAcademy.Models.Instructor", b =>
                {
                    b.HasOne("ITIAcademy.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId");

                    b.HasOne("ITIAcademy.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITIAcademy.Models.Trainee", b =>
                {
                    b.HasOne("ITIAcademy.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITIAcademy.Models.TraineeCourse", b =>
                {
                    b.HasOne("ITIAcademy.Models.Course", "Course")
                        .WithMany("TraineeCourses")
                        .HasForeignKey("CourseId");

                    b.HasOne("ITIAcademy.Models.Trainee", "Trainee")
                        .WithMany("traineeCourses")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("ITIAcademy.Models.Course", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("TraineeCourses");
                });

            modelBuilder.Entity("ITIAcademy.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("ITIAcademy.Models.Trainee", b =>
                {
                    b.Navigation("traineeCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
